name : Testing workflow_dispatch

on:
  workflow_dispatch: 

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo " Manually triggered workflow! - Karan"


