name : To_check_repos

on:
  pull_request:
    branches:
    - main

jobs:
  Job1:
    name: Choosing the runner
    runs-on: ubuntu:latest

    steps:
      -name: Check out repo 
      uses: actions/checkout@v5
      

        
    
  
